# Generated by Django 5.0.2 on 2024-02-08 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_cita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abogado',
            old_name='nombre',
            new_name='nombrea',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='nombre',
            new_name='nombrec',
        ),
    ]
