# Generated by Django 5.0.2 on 2024-02-08 05:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_rename_nombre_abogado_nombrea_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipos_casos', models.CharField(choices=[('Penal', 'Penal'), ('laboral', 'Laboral'), ('Civil', 'Civil')], default='Penal', max_length=10)),
                ('Estado', models.CharField(choices=[('Proceso', 'Proceso'), ('Cerrado', 'Cerrado')], default='Proceso', max_length=10)),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('abogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='login.abogado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='login.clientes')),
            ],
        ),
    ]
