# Generated by Django 3.2.24 on 2024-02-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_casos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='correo',
            field=models.CharField(max_length=144),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='correo',
            field=models.CharField(max_length=144),
        ),
    ]
