# Generated by Django 3.2.24 on 2024-02-08 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20240208_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField()),
                ('descripcion_documento', models.TextField()),
                ('archivo_adjunto', models.TextField()),
                ('otros_campos', models.CharField(blank=True, max_length=255, null=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.casos')),
            ],
        ),
    ]
