# Generated by Django 3.2.24 on 2024-02-08 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_abogado_tipos_especialidad'),
        ('login', '0007_documentos'),
    ]

    operations = [
    ]
