# Generated by Django 3.2.24 on 2024-02-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_merge_0007_abogado_tipos_especialidad_0007_documentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentos',
            name='otros_campos',
        ),
        migrations.AlterField(
            model_name='documentos',
            name='archivo_adjunto',
            field=models.FileField(upload_to='documentos/'),
        ),
    ]
