# Generated by Django 3.2.24 on 2024-02-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_remove_abogado_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='abogado',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$ksGzQdAegcgVxzdZXcvSnk$wQGqYLPC9UkUerYDorj/fUSkQFCzU/3MnBgjXKcMnPo=', max_length=128),
        ),
        migrations.AddField(
            model_name='abogado',
            name='usuario',
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
