# Generated by Django 3.2.24 on 2024-02-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20240210_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$sOuoq92Yu24wnJbQskzcWY$irDn9Bcae87hZL1HaLKmMQ673FcJrSWjcRAqd3r+SwY=', max_length=128),
        ),
    ]
