# Generated by Django 3.2.24 on 2024-02-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_alter_abogado_contraseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$GZuYM7QYO6dx2RIYZh7ClT$+LgNN4gS3C2+nS+jJldgXfr3m/kjzOyH9Kfa+mbfgBQ=', max_length=128),
        ),
        migrations.AddField(
            model_name='clientes',
            name='usuario',
            field=models.CharField(default='default_username', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$HxftUpUAuiMuMwPJL2J8ZI$0yiskBD4c6tg1w8CgLBpD23kmk18rcq39tmerbiPfHQ=', max_length=128),
        ),
    ]
