# Generated by Django 3.2.24 on 2024-02-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20240210_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$xhm0KkMScei7SwYuKqPVXW$qqt1zuIMbM6WzRHwCHO9IR/ZHxaFhX0oa3HcloO/EME=', max_length=128),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$F7tSHWGVp14LjSlnpIOVZw$lVBBxtzLLhhNfbV2WbmqYQaC9ApuPkX0I+2lyfoPbFk=', max_length=128),
        ),
    ]
