# Generated by Django 3.2.24 on 2024-02-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20240210_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$FtV4yUL6hBVpAiC77leoZV$w4G6Q4bkBX/o4YnqWD+65IFFHBfC0quTGMqQBkP9IRA=', max_length=128),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$i9yh6nI1ByG2UG0wG7RRdi$44eWsS6xG/w2c36aPdcXqM1YwZ08BveIECeissMpB1A=', max_length=128),
        ),
    ]
