# Generated by Django 4.2.7 on 2024-02-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_alter_abogado_contraseña_alter_clientes_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$600000$Y5EXY1HpyvQj0Yue6kDnua$ebXfCw+YfYsyKvZ2qr//+1YZuj7obreS++9iBQujCpc=', max_length=128),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$600000$foS65Pzu0Yldf3gaRhKqHF$nMF0EAGvRqHhGpPcoShk48GDrw6VZyfyhAD32M+TvUM=', max_length=128),
        ),
    ]
