# Generated by Django 4.2.7 on 2024-02-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_alter_abogado_contraseña_alter_clientes_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$600000$y6m8V9CpqRVJFCxyIsf3QP$KgOCB2cPGenxoFlH42sOC8rDr4s6n/VdsBeloKNbiL8=', max_length=128),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$600000$ZwxusHRoBQpvmhaAmLU9Ni$ao0UNgfQI5xRYx+A2NF+rHX/sLW/dq7yJdU28JRAJJ8=', max_length=128),
        ),
    ]
