# Generated by Django 3.2.24 on 2024-02-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_alter_abogado_contraseña_alter_clientes_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$rDlPeMZGs9nLl4r09Oy8on$qKE1558R5gYfV92YZgXi46i5x5fObRSNPSGXXAxg/hA=', max_length=128),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$xNT1UOsRCunfiFPyqY6WCz$HmvBDzVPF50O9qjkCfUKZq7HC10EN+CTS0dFb2oMkFc=', max_length=128),
        ),
    ]
