# Generated by Django 3.2.24 on 2024-02-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_auto_20240215_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$d4mF9rbQvT5NrEVpnPft6g$aMNXmxrB99I2CbPJzsBwzAXQ0OSmbKQkZcf5VZLLQaA=', max_length=128),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$7l2Q7jRVp91OlcpHA1XDLz$Wn41L5lIERXur3qMmva2fe5r2qlVpAxpd/WmpMbu3Cw=', max_length=128),
        ),
    ]
