# Generated by Django 3.2.24 on 2024-02-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_auto_20240215_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$K0esYjcA4gucFiv7AEUX0g$5Eu3N2CwHVxEuJHMkpNzt2v5qbShdGpdzdV/9bCVNoc=', max_length=128),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$5cnYV6bJel4qzdg5tmYNs4$+bxRQz09YfMY62G4MCPPhX2YfR+Sds5zowiOWFS13r0=', max_length=128),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='archivo_adjunto',
            field=models.FileField(blank=True, upload_to='documentos/'),
        ),
    ]
