# Generated by Django 4.2.7 on 2024-02-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_alter_abogado_contraseña_alter_clientes_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$600000$rGFpDDP42ioVQLgLL4qAHM$w7PxmrSvGM+53ubVDpmFtct0xa1361ZMSDrx3Xt6em0=', max_length=128),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$600000$Wwch35vUaDX4KbUNKLlME4$1Pf9s2yAfxjaQ4dqkqJ/1EcAwcASJKPDVcKdN0f8bmc=', max_length=128),
        ),
    ]
