# Generated by Django 3.2.24 on 2024-02-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_auto_20240215_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$EncyN1ILcVsIj0KIylh5ji$/OT7PCci/wzgpi+vavquHfupISiD6TgJXj6XrY8WU5M=', max_length=128),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$7IhymA9IUHkT8rdssqCpWA$evW7sUU6kUwfGcGtuoLl9SRsQbXM5/8MwZ9opb1jXQI=', max_length=128),
        ),
    ]
