# Generated by Django 3.2.24 on 2024-02-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_auto_20240215_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$mYlOjqsg5OHhnkF1JZOWzj$CrnDAABnKHcyFWD3rjpelvld6i29kSNzvdobZm5vwq8=', max_length=128),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$KwF5PplepABGQh1QgMBhtN$JAJp80Hzu4BX/dbzq3hbkB706uNJEJ2ns4Iv1/GJTUQ=', max_length=128),
        ),
    ]
