# Generated by Django 3.2.24 on 2024-02-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_auto_20240215_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$FVs3L52qt0o1mk3Jbv4ntU$dYLGPbuepO9I8JQVL1mK/cq6VNoVyfOYCjvLsL68e6g=', max_length=128),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$uu0w2iRW6zQ3vCmOeMMwAI$yGXDvoVfm4J1bnjNNS9UrYitk/eRGQXa6y8KRF+IXFs=', max_length=128),
        ),
    ]
