# Generated by Django 3.2.24 on 2024-02-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_auto_20240215_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$Awr6GvDTaVS6VJ8BYb7M2z$Rq56X1/EIegHIAy/HgCB/0K0w0XVBezEPLprhjRdkYE=', max_length=128),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$wnoVGhmNpDPfN0ZOtwyFHv$YWleKMlVOXXiTz9bpLdmtMzj3hHgQNjNJ16v0DXXuiU=', max_length=128),
        ),
    ]
