# Generated by Django 3.2.24 on 2024-02-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_auto_20240215_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$Rf0j5VM3nB4R3KxLkkXfTv$wfwu6oe1PH5ytc9U+hg3TRULom3yesupkG82520QSnI=', max_length=128),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$6D7kvPPEoleNej7GR5XbFB$g7QKjDzArTO7HwvaYciqxPehZmmWmCMCJIWHDKnTvVY=', max_length=128),
        ),
    ]
