# Generated by Django 3.2.24 on 2024-02-16 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_auto_20240215_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$SbeLSkz7tUJr7OFvJXqae1$1H2N/1MeUc/4/G6yyRjDm/oAitHFvjzu/8TeXg2krdg=', max_length=128),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$aBTQmoLfmJV4Z9GxHKLjJW$mkIRCS+1BOa2a4QQcsD0Rxq7EGWOfT97waSl3v7+6sI=', max_length=128),
        ),
    ]
