# Generated by Django 3.2.24 on 2024-02-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0028_auto_20240215_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$LBwCyKaeDqe0fRzJwTsXur$V6GOi5/Pobe+1SN5baR9n5lLUKlpdSk0Y5AEJ3Sih6k=', max_length=128),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$NHW0DYqridr6zh7tsbAnaf$6H8W4gGI47zpsxUs6obcHCDVAwjcnk1pzwZdzQBQ8Xo=', max_length=128),
        ),
    ]
