# Generated by Django 3.2.24 on 2024-02-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0029_auto_20240216_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$VfuAlwgAezft64VBlnJK1U$tRixVs64Llu5lM/f9looO/8tgIXhr/SgfYgt7Mqtdms=', max_length=128),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$quN0fv1yMB5VMKnKXkmN1o$1JDSnU9YwNHNADgVrsaq0b+6Bggh0rMpVIw32P8OSHY=', max_length=128),
        ),
    ]
