# Generated by Django 3.2.24 on 2024-02-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0030_auto_20240216_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$AMXnSIRgrIuxDMhuJYcAP7$IrCMM0eru8lRIkjMB6KzcoxjwzrSaEzsOo65xXyteak=', max_length=128),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$zRbKfb5SkG32w1h2al4HqG$E5KMBepKofJ2Sp2k2a91Ldie+jxp/8Hyu57ODNMvWMg=', max_length=128),
        ),
    ]
