# Generated by Django 3.2.24 on 2024-02-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0031_auto_20240216_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$yCCGciedfWEiorCFP3GD3U$GMUH4HJyvQEf6FCgHuLSxs/GHWZP5LT+8buajOG7Nqs=', max_length=128),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$Pw7CORV8ajSFJQA6moHU85$wrXuXR7dQr/xnYMmErC9/I4atnMPSMOC2RnKyyB2Cy4=', max_length=128),
        ),
    ]
