# Generated by Django 3.2.24 on 2024-02-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0032_auto_20240216_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$wc98Da93JBkMG2WWJtkq3X$8bgtnw+ZDXmodAV+173H2X7ieueKrqRx2qZpDRDS2gc=', max_length=128),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$yTZVDLlYJRYl7ReNWC2BkS$AiuzXOwYfUnUphVKL5As8b9KLx0ouzves/1HpooJAzI=', max_length=128),
        ),
    ]
