# Generated by Django 3.2.24 on 2024-02-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0033_auto_20240216_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$Tlu3JydJLi5C8QvKcd9LaO$0/8cOvaaxgvnqnuWvJxqUhFI22CmjcxU+06z8T6eVQQ=', max_length=128),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$UNkAMDZjIcscVeMKzWtGEO$6JGO46Oj0cOa5wmsT6g6/5xJ22ZYrNKU2vcAn2Og1rw=', max_length=128),
        ),
    ]
