# Generated by Django 3.2.24 on 2024-02-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0034_auto_20240216_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$zNZZ74xyAUJH0I4wbHpZpV$P3eRjDBk4Dmi0kBCoL+izxVVS1w+JypKJJia3eUjyrY=', max_length=128),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$eYD0YnSugbQipnSOp4Eqs2$Ju7cwKbWAbP5GcLQabEdHa3T9CeOYvJyM40GEPeSU0g=', max_length=128),
        ),
    ]
