# Generated by Django 3.2.24 on 2024-02-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0035_auto_20240216_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$ndovpCMvwhJZPEWw2IVm5k$dFc1Ib6cB+ov4PsKY0NWNuuHxz+lTljtpeC6EuJVFjs=', max_length=128),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$260000$QtiCObnvMUktxvUIN5gcCR$lf2e3HgomrF4CPd9/qJiWsgnsarUxDaFqj0AHvnsPZs=', max_length=128),
        ),
    ]
